//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decent.IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayIncome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DayIncome()
        {
            this.DaySells = new HashSet<DaySell>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Sell { get; set; }
        public double Cost { get; set; }
        public double Payment { get; set; }
        public double Benifit { get; set; }
        public Nullable<int> DayCostId { get; set; }
    
        public virtual DayCost DayCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaySell> DaySells { get; set; }
    }
}
