//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decent.IMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerNewProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellerNewProduct()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string Name { get; set; }
        public string ProductName { get; set; }
        public int ProductCategoryId { get; set; }
        public int ProductAmount { get; set; }
        public double PriceRate { get; set; }
        public double TotalPrice { get; set; }
        public string Discount { get; set; }
        public double AfterTotalPrice { get; set; }
        public double CarryingCost { get; set; }
        public double AfterPriceRate { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
